language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
before_install:
- "openssl aes-256-cbc -K $encrypted_7d81a13424f8_key -iv $encrypted_7d81a13424f8_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d"
- sudo pip install codecov
before_script:
- chmod 600 ~/.ssh/id_rsa
script: ./sbt coverage test
notifications:
  email: false
  hipchat:
    rooms:
      secure: H2g8rdi7W4ZiU49IGozXTFvaugch84rqp/XiNnIAB1rID4R68p8TV7Khxz8JaitNqu4U4Iw2Z5y0aYJLdu+MyrrMsmpZ1aKvOaVfyDh+oRLpuM+pjsyCrzQVWpnYKFLJ7eesTK5ELx74I/h1tsuM7o8sCgLf5Wf7oDuXP737V20=
    on_success: change
    on_failure: change
    notify: true
after_success: ./after-success.sh
