language: scala
scala:
- 2.11.1
jdk:
- oraclejdk8
before_install: sudo pip install codecov
script: ./sbt clean coverage test
notifications:
  email: false
  hipchat:
    rooms:
      secure: H2g8rdi7W4ZiU49IGozXTFvaugch84rqp/XiNnIAB1rID4R68p8TV7Khxz8JaitNqu4U4Iw2Z5y0aYJLdu+MyrrMsmpZ1aKvOaVfyDh+oRLpuM+pjsyCrzQVWpnYKFLJ7eesTK5ELx74I/h1tsuM7o8sCgLf5Wf7oDuXP737V20=
    on_success: change
    on_failure: change
    notify: true
after_success: codecov
deploy:
  provider: heroku
  api_key:
    secure: SlhotCW8l/Q7bvTZ6ubR2N6OfRaw4lPnL9cshyER4CnWUY2s7ZlZopEkVUZv5GC9RBdq16iOUC9JXLa+1lZieJ30RVN/EtwH/jHUtUadRB2yBAY27iVRyL1G4QzsHSkXZmNSP+CtACO9cLjR/MY1CugwOddijyUQ0aYqTdDsPmA=
  app: dry-depths-2035
