language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
before_install:
- sudo pip install codecov
before_script:
- chmod 600 ~/.ssh/id_rsa
script: ./sbt coverage test
notifications:
  email: false
  hipchat:
    rooms:
      secure: H2g8rdi7W4ZiU49IGozXTFvaugch84rqp/XiNnIAB1rID4R68p8TV7Khxz8JaitNqu4U4Iw2Z5y0aYJLdu+MyrrMsmpZ1aKvOaVfyDh+oRLpuM+pjsyCrzQVWpnYKFLJ7eesTK5ELx74I/h1tsuM7o8sCgLf5Wf7oDuXP737V20=
    on_success: change
    on_failure: change
    notify: true
after_success:
- codecov
- ./sbt debian:packageBin
